### ISSUE TITLE
Windows Bugs

### ISSUE THREAD

**Issue by justin-ho** [justin-ho/passwd-mng#10]
### Description
NameError: global name 'pwd ' is not defined 

### Expected behavior
Error should not show up on Windows system.

**Comment by justin-ho** [comment]
If you're only using the pwd library to get a unix users username you could use the getpass library that I used. It doesn't seem to have issues with windows and there's a function called getuser() which accomplishes the same thing

**Comment by ElliotIto** [comment]
That would work, but just something of note that users can impersonate others because this is based on the environment variables (http://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python#).

**Comment by justin-ho** [comment]
@ElliotIto ah good catch! Disregard that then

**Comment by justin-ho** [comment]
current error on windows:

![13646847_1377691835577531_477703657_o](https://cloud.githubusercontent.com/assets/11323114/17269799/5809fee6-55ee-11e6-8bce-6aa81bee51df.png)

**Comment by ElliotIto** [comment]
@justin-ho Will be looking into it - not sure why encrypted_key is returning as an empty string on Windows.

**Comment by justin-ho** [comment]
also in the encFile.py you have :
`try:
    import pwd
except: ImportError`

i think it should be: 
`try:
    import pwd
except ImportError:
    """Do Nothing"""
` 

basically i think the colon is in the wrong place
