### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by justin-ho** [justin-ho/passwd-mng#11]
### Description
This bug happens when the user enters an identifier that doesn't exist in the data store. We're currently not doing a check for whether or not what is returned is valid data.

### Steps to reproduce
1. start application 
2. enter your password
3. select option 2 to get credentials
4. enter an invalid identifier

### Expected behavior
We should be gracefully telling the user that the identifier does not exist in the data store rather than python complaining of an IndexError

**Comment by ElliotIto** [comment]
@justin-ho Checked on the code the issue appears resolved.

**Comment by justin-ho** [comment]
fixed in b0817d915ff1f9c
