### ISSUE TITLE
Create deconstructor for the UACC class

### ISSUE THREAD

**Issue by justin-ho** [justin-ho/passwd-mng#17]
### Description
Can follow this http://www.tutorialspoint.com/python/python_classes_objects.htm
under the section `Destroying Objects (Garbage Collection)`
we can use the deconstructor to destroy UACC objects

**Comment by justin-ho** [comment]
should use #18

**Comment by barakaki** [comment]
can we close this issue?

**Comment by justin-ho** [comment]
I guess we don't really need it so I'll just close it.
