### ISSUE TITLE
Python del statement

### ISSUE THREAD

**Issue by justin-ho** [justin-ho/passwd-mng#18]
I did some research on the python [del statement](https://docs.python.org/2/tutorial/datastructures.html#the-del-statement) and it looks like it basically dereferences the variable(s). 

Do you guys think we should use the Python del statement to dereference variables with sensitive information after we're done using that information?

**Comment by ElliotIto** [comment]
Yes, that would work. It would be the preferred solution than my value reassignment.

**Comment by justin-ho** [comment]
@ElliotIto yea I didn't know about this and I pretty much did the same thing as you
