### ISSUE TITLE
Write Unit tests for important functions that you created

### ISSUE THREAD

**Issue by justin-ho** [justin-ho/passwd-mng#20]
### Description
This is for section 1 of our report (Dynamic Analysis) 

I know there's a lot of functions though so we probably won't have a tests for each function, but for now lets cover the important ones. Let me or @barakaki know if you need help though. 
 
we will be using PyUnit which is a standard unit testing framework for python. The docs are [here](https://docs.python.org/2.7/library/unittest.html).

**Comment by ElliotIto** [comment]
Is this on a separate branch, master, or individual branch for features?

**Comment by justin-ho** [comment]
Hmmmm I guess a separate branch maybe?
