### ISSUE TITLE
Creation of new Key Generation

### ISSUE THREAD

**Issue by ElliotIto** [justin-ho/passwd-mng#22]
This is for finding a new method of key generation. It is recommended that we find a new method of generating keys as the key can be found, I am not sure what would be a better method of creating a new key.

**Comment by justin-ho** [comment]
@ElliotIto could you explain this to me a little more? I might be able to work on it if I get a better understanding of this.

**Comment by ElliotIto** [comment]
Basically the key for encrypting and the key being used to encrypt the user's information can be the same. There is a key (key1) that encrypts the key (key2) that is used for encrypting the user's data.

Key1 is generated by the following:
key = running directory + key
while key < 32
    key += running directory + username
key = last 32 characters of key

Key2 is generated by the following:
username + running directory
pad(key2)
   if key2 < blocksize
        key2 += (blocksize - length of key 2) *chr(blocksize - length of key2) 

If key2 is less than block size, pad the key with the character whose integer value is block size - length of key until it is of length block size.


While this is good for a temporary generation, this brings up the issue of not having a unique key that can secure information (ie person finding directory of the file and creating a new user with the same name - on a different computer).

**Comment by justin-ho** [comment]
What if we some how use the password that the user enters to use the application, to make the key unique? The password that the user has to set on their first initial run of the application.

**Comment by ElliotIto** [comment]
We could, but it would most likely be using the encrypted form.
