### ISSUE TITLE
UI output improvement 

### ISSUE THREAD

**Issue by barakaki** [justin-ho/passwd-mng#25]
Complete these steps before submitting the issue.

- [ ] Assign the relevant Labels
- [ ] Assign the applicable Milestone
- [ ] Assign to the appropriate person

### Description
When the user adds a credential and inputs something wrong. The terminal displays what is wrong along with the options menu. This issue will fix it so when the user inputs doesn't meet our requirement, it will display our requirements then say press anything to continue. When the user presses anything, then they will be prompted with the options menu.

### Steps to reproduce
1.
2.
3.

### Expected behavior
_What should happen_

**Comment by justin-ho** [comment]
@barakaki we should limit it to 1 button and inform the user which button to press rather than anything.

**Comment by barakaki** [comment]
kks, so if the user doesn't input the right key then just say please try again? lol

**Comment by justin-ho** [comment]
hmmmm actually nvm disregard what I said
