### ISSUE TITLE
Not saving passwords after exit

### ISSUE THREAD

**Issue by barakaki** [justin-ho/passwd-mng#26]
Complete these steps before submitting the issue.

- [ ] Assign the relevant Labels
- [ ] Assign the applicable Milestone
- [ ] Assign to the appropriate person

### Description
There is a problem when I try to get credentials after I quit the program. I can add the credentials and get the information back as long as I don't exit the program. Once I exit the program, the get credentials cannot find the credentials that were saved in the previous sessions. 

### Steps to reproduce
1.
2.
3.

### Expected behavior
_What should happen_

**Comment by ElliotIto** [comment]
@barakaki I did a pull for the latest changes and it works for me using both Linux and Windows (using windows 10).

1. Are you using Linux or Windows?
2. What branch are you on?
3. Are there any errors?
4. Can you provide what the contents of the storange.enc file?

Linux: Open terminal and cd to directory. Once in the directory use the command: cat storage.enc

Windows: Open command prompt and cd to directory. Once in directory use the command: type storage.enc.

Let me know if you have any questions on these questions.

**Comment by barakaki** [comment]
1. windows
2. issue_25
3. no errors
4. »Äº/3èΣδ╦╖,Σ╝}T[Ä╚Fô|Htφ║√╜cº
S2KtA38m4LT13kq2gXK1lESba7dBvk8TFMenz6ph7bRsGxOjdKnnAf38VTt1qjRUmn3uFCEVt0mLBm9TeVvRVp8j0UJXLOD23E1KAkFebLA=
2Rv4BiA926NehpAKD57s4dMRAqLTP4UA/FswsTuRbKf8WOT++aG+J7JQH0kPEcHjxPT6pRx2vGtIDcYjaRVkfp6kcgn+ENfUWUv88+08NHgzmaJ0fE7Jbs/j9dSiIjXQNA/P+lzq5BbN98mW2vlZqLee97LshPTLF/pR//0DMSE4tCAVxDhW63NvkVwQDs33/7HgctN8Fe7FLa9oqf/9jAr9nWEeeqDUMvUUh3T/FaVjXxOuChuCAzj6gqZjVD3eW+UV6ei5mPA1Y2U5QIrad5Q6UQCXMTbIsx2gxe8vsdgZJ1QnClJ8r7XLAZFcRp3ocX/ttZJxc0s1HusHJYz53m03epkGE+Laqigb30KZbX3X68Ai3JKvVFbU+U6NyL5n

**Comment by ElliotIto** [comment]
Please push issue_25 to Github for me to review.

**Comment by ElliotIto** [comment]
@barakaki Will take a bit to debug - getting errors right now (Using Windows due to issue that is noted).

**Comment by ElliotIto** [comment]
@barakaki Okay I did a push that should fix it. Let me know if it does.

**Comment by barakaki** [comment]
It works! What was wrong with it?

**Comment by ElliotIto** [comment]
Not sure. I changed how the key was generated. So I don't know how that affected it...

**Comment by justin-ho** [comment]
is this fixed? If so we can create a pull request and merge with master

**Comment by ElliotIto** [comment]
@justin-ho From the looks of it yes.

**Comment by justin-ho** [comment]
@ElliotIto not sure which branch you used, can you make a pull request so we can merge with master?

**Comment by barakaki** [comment]
Actually there might be a problem still. Try add 2 different credentials and then quit the program. Re log in and try and get those credentials that you added before. For me, both can't be found. It works perfectly when there is only one credential saved. I'm not sure if this was a problem before or not.
