### ISSUE TITLE
Termination of Python Ctrl + D/Z

### ISSUE THREAD

**Issue by ElliotIto** [justin-ho/passwd-mng#27]
### Description
When at the main menu, Ctrl+D on Linux and Ctrl+Z on Windows will get an EOF error.

### Steps to reproduce
1. Enter in password to authenticate.
2. At the main menu enter in Ctrl+D on Linux or Ctrl+Z on Windows.

### Expected behavior
Code should exit gracefully.

**Comment by justin-ho** [comment]
hmm strange that this would happen when I have the exception for keyboard interrupts....might be something that can't be fixed, but I'll look into it when I get home

**Comment by justin-ho** [comment]
I'll work on this one

**Comment by justin-ho** [comment]
fb3c71325d6d69fd876c9a7ca17e260fcb2c3acc
