### ISSUE TITLE
Issue 25 Linux Bugs

### ISSUE THREAD

**Issue by ElliotIto** [justin-ho/passwd-mng#28]
### Description
Bellow are the current bugs found in Linux for branch 25. This list will be updated when bugs are fixed.

### Bugs
1. Import error with Windows only module msvcrt

#### Bug 1
1. Starting the program will get import error

#### Expected behavior - Bug 1
Import error should be ignored (see code below)  and any code that uses the module should have a check to see if the module was imported.
```
try:
    import mscvcrt
except ImportError:
pass
```

**Comment by justin-ho** [comment]
Does anyone want to work on this? If not I can take it, let me know

**Comment by justin-ho** [comment]
I'll work on it

**Comment by justin-ho** [comment]
Fixed in 91005e7d04d1107d6c631d260dacb9bb0279368f
