### ISSUE TITLE
Update user account feature

### ISSUE THREAD

**Issue by justin-ho** [justin-ho/passwd-mng#34]
### Description
Implementation of the Update user account feature.

Requirements:
- should take an identifier as input 
- get the user to enter the new username and new password for that account
- should validate the info as well

**Comment by justin-ho** [comment]
@ElliotIto @barakaki not sure which one of you wants to work on this. When you guys figure it out please unassign the person that's not working on it

**Comment by ElliotIto** [comment]
@justin-ho Okay, this was done, I'll put in a pull request for review.
