### ISSUE TITLE
Removal of .eta file gives access to the previous users credentials

### ISSUE THREAD

**Issue by justin-ho** [justin-ho/passwd-mng#39]
### Description
If the .eta file is removed and a new password is created. The user can view the credentials of the previous user. This is related to #22 , but a temporary fix should be implemented until then. 

### Steps to reproduce
1. start the application for the first time 
2. create a new password for authentication
3. add credentials
4. quit the program
5. remove the .eta file
6. start the program and create a new password for authentication
7. get one of the previous users credentials

### Expected behavior
new user should not be able to access the previous users credentials.

**Comment by barakaki** [comment]
@ElliotIto 
There's also another problem.
1. start the application for the first time(no .eta file and storage file)
2. create a new password
3. add credentials
4. quit the program
5. re log in
6. get credentials

when you try and get the credentials, it cannot be found. This only happens for the first credential being added. If you were to add two, facebook and myspace (in that order), it can't get facebook. I don't know if this has something to do with the getting key or the encryption.

**Comment by ElliotIto** [comment]
@justin-ho So we are assuming that people will be sharing the same user account?

**Comment by justin-ho** [comment]
not necessarily, but I think I was just trying to be more robust

**Comment by ElliotIto** [comment]
Works for me.
